blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/DTCurrie
    about: For questions that are not a bug report or a feature request, contact the maintainer directly.
